config/routes.rb
Rails.application.routes.draw do
  root :to => "products#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products, only: [:index, :show] do
    member do
      get :add_to_cart
      get :remove_from_cart
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :carts, only: [:index] do

  end

  resources :orders, only: [:create] do
    collection do
      post :notify
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    products_ids = cookies['cart']&.split(' ')
    @products = Product.where(id: products_ids)
  end
end

app/controllers/orders_controller.rb
require 'net/http'
require 'uri'

class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token


  # POST
  def create
    clear_cart
    access_token = get_access_token
    sum_up_products

    response = create_payment(access_token)

    payu_order_id = response['orderId']

    Order.create(payu_order_id: response['orderId'],
                 payment_status: 'INITIALIZED',
                 details: @products_details)


    redirect_to response['redirectUri']
  end

  # POST - callback endpoint that receives payments status updates from PayU
  def notify
    payu_order_id = params['order']['orderId']
    order = Order.find_by(payu_order_id: payu_order_id)

    if order.present?
      order.update(payment_status: params['order']['status'])
    end

  end

  private

  def clear_cart
    cookies.delete :cart
  end

  def sum_up_products

    products_ids = params['quantity'].keys
    products = Product.where(id: products_ids)

    @total_amount = 0.0
    @products_details = products.map do |product|
      quantity = params['quantity'][product.id.to_s]
      @total_amount += (product.price * quantity.to_i).to_d

      {
        'name' => product.name,
        'unitPrice' => convert_to_pln_in_gr(product.price),
        'quantity' => quantity
      }
    end
  end

  def convert_to_pln_in_gr(amount)
    (amount * 100).to_s.delete_suffix('.0')
  end

  def get_access_token
    uri = URI.parse("https://private-anon-55340bc7ef-payu21.apiary-mock.com/pl/standard/user/oauth/authorize")
    request = Net::HTTP::Post.new(uri)
    request.content_type = "application/x-www-form-urlencoded"
    request.set_form_data(
      "client_id" => ENV['PAYU_CLIENT_ID'],
      "client_secret" => ENV['PAYU_CLIENT_SECRET'],
      "grant_type" => "client_credentials",
    )

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end

    JSON.parse(response.body)['access_token']
  end

  def create_payment(access_token)
    uri = URI.parse("https://secure.payu.com/api/v2_1/orders/")
    request = Net::HTTP::Post.new(uri)
    request.content_type = "application/json"
    request["Authorization"] = "Bearer #{access_token}"
    request.body = JSON.dump({
      "notifyUrl" => "#{ENV['APP_URL']}/orders/notify",
      "continueUrl" => "#{ENV['APP_URL']}/products",
      "customerIp" => "127.0.0.1",
      "merchantPosId" => '145227',
      "description" => "e-shop",
      "currencyCode" => "PLN",
      "totalAmount" => convert_to_pln_in_gr(@total_amount),
      "products" => @products_details
    })

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end

    JSON.parse(response.body)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order(created_at: :desc)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/1/update_cart
  def add_to_cart
    product_id = params[:id].to_s
    if cookies['cart'].present?
      product_ids = cookies['cart'].split(' ').push(product_id).uniq
      cookies['cart'] = { value: product_ids.join(' ') }
    else
      cookies['cart'] = { value: product_id }
    end

    redirect_to products_path, notice: 'Product was successfully added to the cart.'
  end

  def remove_from_cart
    if cookies['cart'].present?
      product_ids = cookies['cart'].split(' ') - [params[:id].to_s]
      cookies['cart'] = { value: product_ids.join(' ') }
      redirect_to carts_path, notice: 'Product was successfully removed from the cart.'
    else
      redirect_to products_path, notice: 'Something went wrong. Please search for another product'
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <div class="panel panel-info">
      <form action="/orders" method="post">
        <div class="panel-heading">
          <div class="panel-title">
            <div class="row">
              <div class="col-xs-6">
                <h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
              </div>
              <div class="col-xs-6">
                
                <%= link_to products_path, class: "btn btn-primary btn-sm right btn-block" do %>
                  <span class="glyphicon glyphicon-share-alt"></span>
                  Continue shopping
                  <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <% if @products.present? %>
          <% @products.each do |product| %>
          <div class="row">
            <div class="col-xs-2"><img class="img-responsive" src="http://placehold.it/100x70">
            </div>
            <div class="col-xs-4">
              <h4 class="product-name"><strong><%= product.name %> </strong></h4>
              <h4><small><%= product.description %> </small></h4>
            </div>
            <div class="col-xs-6">
              <div class="col-xs-6 text-right">
                <h6><strong><span id="<%= product.id %>-price"><%= product.price %></span> <span class="text-muted">x</span></strong></h6>
                <input type="hidden" name="price[<%= product.id %>]" value="<%= product.price %>">
              </div>
              <div class="col-xs-4">
                <input id="<%= product.id %>-quantity" name="quantity[<%= product.id %>]"type="text" class="form-control input-sm" value="1" onchange="calculateTotalValue(<%= @products.pluck(:id) %>)">
              </div>
              <div class="col-xs-2">
                <button type="button" class="btn btn-link btn-xs">
                <%= link_to remove_from_cart_product_path(product.id) do %>
                <span class="glyphicon glyphicon-trash"> </span>
                <% end %>
                </button>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
          <hr>
        </div>
        <div class="panel-footer">
          <div class="row text-center">
            <div class="col-xs-9">
              <h4 class="text-right">Total <strong><span id='total'>50.00</span> PLN</strong></h4>
            </div>
            <div class="col-xs-3">
              <button type="submit" class="btn btn-success btn-block">
              Checkout
              </button>
            </div>
          </div>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
window.onload = calculateTotalValue(<%= @products.pluck(:id) %>);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Eshop</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Eshop", products_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
        
          <li><%= link_to 'Cart', carts_path %> </li>
        </ul>
      </div>
    </div>
  </nav>

  
  <div class="container main-container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>


<div class='row'></div>
    <%= yield %>
  </div>
</body>
</html>

app/views/products/index.html.erb
<div class="page-header">
  <h1>Products</h1>
</div>

<% @products.each_slice(3) do |products| %>
<div class="row mt-5">

  <% products.each do |product| %>
  <div class="col-sm-3">
    <div class="col-item">
      <div class="photo">
        <img src="http://placehold.it/350x260" class="img-responsive" alt="a" />
      </div>
      <div class="info">
        <div class="row">
          <div class="price col-md-12">
            <h5>
              <%= product.name %>
            </h5>
            <h5 class="price-text-color">
              <%= product.price %> PLN
            </h5>
          </div>

        </div>
        <div class="separator clear-left">
          <p class="btn-add">
            <span class="glyphicon glyphicon-shopping-cart"></span> <%= link_to 'Add to cart', add_to_cart_product_path(product.id) %>
          </p>
          <p class="btn-details">
            <span class="glyphicon glyphicon-list"></span> <%= link_to 'More details', product %>
          </p>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/products/show.html.erb
<div class="page-header">
  <h1><%= @product.name %></h1>
</div>

<div class='row'>
  <div class="col-md-8 col-md-offset-2">
    <div class="col-item">
      <div class="photo">
        <img src="http://placehold.it/350x260" class="img-responsive" alt="a" />
      </div>
      <div class="info">
        <div class="row">
          <div class="price col-md-6">


            <p>
              <%= @product.description %>
            </p>
            <h2 class="price-text-color">
              <%= @product.price %>
              <%= link_to add_to_cart_product_path(@product.id), class: 'btn btn-success' do %>
                <span class="fa fa-shopping-cart"></span>
                Add to cart
              <% end %>
            </h2>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<div class='row'>
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
</div>